language: ruby
cache: bundler
rvm:
  - '2.7.1'
services:
  - postgresql
script:
  - bundle exec standardrb
  - RAILS_ENV=test bundle exec rake db:drop
  - RAILS_ENV=test bundle exec rake db:create
  - RAILS_ENV=test bundle exec rake db:migrate
  - bundle exec brakeman -zq --ensure-latest
  - bundle exec rake spec
addons:
  chrome: stable
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database doubleunion_test;' -U postgres
env: SECRET_TOKEN=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
